name: Android APK Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
      
    - name: Fix gradlew permissions
      run: |
        cd android
        chmod +x gradlew
      
    - name: Check Gradle version
      run: |
        cd android
        ./gradlew --version
      
    - name: Create google-services.json
      run: |
        echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json
        
    - name: Fix entry point for Expo Router
      run: |
        # Create a proper entry point for Expo Router
        echo 'import { registerRootComponent } from "expo";
        import { ExpoRoot } from "expo-router";
        
        // Must be exported or Fast Refresh won't update the context
        export function App() {
          const ctx = require.context("./app");
          return <ExpoRoot context={ctx} />;
        }
        
        registerRootComponent(App);' > App.js
        
    - name: Fix expo-firebase-core build.gradle
      run: |
        echo 'apply plugin: "com.android.library"
        android {
            compileSdkVersion 35
            buildToolsVersion "35.0.0"
            defaultConfig {
                minSdkVersion 24
                targetSdkVersion 35
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
        dependencies {
            implementation "com.google.firebase:firebase-core:21.1.1"
        }' > node_modules/expo-firebase-core/android/build.gradle
        
    - name: Build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk 
